$('.owl-carousel').owlCarousel({
    loop:true,
    margin:8,
    nav:true,
    responsive:{
        0:{
            items:5
        },
        600:{
            items:5
        },
        1000:{
            items:5
        }
    }
})